# Generated by Django 6.0.1 on 2026-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_refactor_college_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(unique=True)),
                ('answer', models.TextField(blank=True, help_text='Enter the answer you want the bot to use for this question', null=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_botque_created_d061e9_idx'), models.Index(fields=['is_answered'], name='core_botque_is_answ_b579ac_idx')],
            },
        ),
    ]
